create database jupyter_db;
use jupyter_db ;
select * from customer_details ;

DESCRIBE customer_details;

ALTER TABLE customer_details
	Modify column age INT Not null,
    Modify column gender enum("Male" , "Female" , "Others") Default "Others";

ALter table customer_details
Modify column customer_id bigint primary key;

-----------------------------------------------------------------------------------
    
-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender , SUM(purchase_amount) as revenue
From customer_details
GROUP BY gender;


-- 2️. Check invalid ranges

SELECT age
FROM customer_details
Where age <0  and age >100 ;

-- Check duplicates

SELECT customer_id, count(*)
From customer_details
Group BY customer_id
Having count(*) <1 ;

-- Which are the top 5 products with the highest average review rating?

Select item_purchased as PRODUCT , avg(review_rating) as AVG_REVIEW_RATING 
from customer_details
group by item_purchased
order by avg_review_rating desc limit 5 ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id , purchase_amount
From customer_details
Where discount_applied = "Yes" and purchase_amount  >=  (select avg(purchase_amount) from customer_details);


-- Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT AVG(purchase_amount) as AVG_PURCHASED_AMOUNT , shipping_type
from customer_details
where shipping_type in ("Express" , "Standard" , "Free Shipping")
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT subscription_status , 
	count(customer_id) as Customer_Id,
	ROUND(avg(purchase_amount) , 2) AS Average_Purchased_Amount,
    sum(purchase_amount) As Total_Revenue
from customer_details
group by subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased , 
count(*) as total_purchased , sum( discount_applied = "Yes" ) AS Discount_Purchased
from Customer_details
Group by item_purchased
order by discount_purchased desc
limit 5;



-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

Select customer_id,
	previous_purchases ,
	case 
    when previous_purchases = 1 THEN "New"
    when previous_purchases between 2 And 10 THEN "Returning"
    else "Loyal"
    End AS Customer_Segment
from customer_details; 


-- Q8. What are the top 3 most purchased products within each category? 

Select item_purchased ,
category ,
count(item_purchased) as counted_items
from customer_details 
group by category , item_purchased
order by category , counted_items desc 
LIMIT 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, 
	count(customer_id) as Repeat_Buyers
from customer_details
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group ,
	sum(purchase_amount) as Revenue_Generated
from customer_details
group by age_group

;
select * from customer_details ;